### ISSUE TITLE
公众号订阅助手

### ISSUE THREAD

**Issue by forever-young-hh** [hzuapps/android-labs-2020#419]
可以在首页看到最近公众号发送的推文，点进去可以阅读文章
可以点进自己主页看到相关信息，如关注量、阅读量之类的信息。

**Comment by zengsn** [comment]
提炼为功能点

**Comment by forever-young-hh** [comment]
功能1：查看最近发送的文章；
功能2：查看相关信息，如：关注量、阅读量之类的信息。

**Comment by forever-young-hh** [comment]
这个项目是修改后的，老师您让我移到#245那个项目里去。所以这个项目不再用。
